apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: bonassolindo/chatforge-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: meu-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: meu-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: meu-secret
              key: POSTGRES_DB
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: meu-secret
              key: POSTGRES_PORT
        - name: BACKEND_PORT
          valueFrom:
            secretKeyRef:
              name: meu-secret
              key: BACKEND_PORT
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: meu-secret
              key: GEMINI_API_KEY